//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolTrackerAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int ToolId { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Notes { get; set; }
        public int Available { get; set; }
        public string AssetNum { get; set; }
        public string Comment { get; set; }
    }
}
